### ISSUE TITLE
Add email address to each modeler

### ISSUE THREAD

**Issue by friedow** [bptlab/blockchain-choreography#5]
It would be nice to have additional information about modelers or at least proposers of a change in order to visualize this information inside the UI. By adding an email address to each modeler, it would be possible to display information form Github or Gravatar Accounts.

**Comment by friedow** [comment]
Can we implement this inside the role management or should this be implemented in an additional package (e.G. profiling service)?

**Comment by MaximilianV** [comment]
See #16. This introduces a new library called `Persons`, which is quite similar to `Roles` but uses another struct and slightly different functions.
